global:
  scrape_interval: 10s
  external_labels:
    monitor: 'prometheus'
# Add prometheus rule file
rule_files:
 - /etc/prometheus/rule_up.yml
# Add alert manager config
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  # This monitors the prometheus instance itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # This monitors the flask application
  - job_name: 'demoapp'
    static_configs:
      - targets: ['localhost:5000']
  # Start scraping Ec2 Instances using service discovery mechanism
  - job_name: 'ec2_instances'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
    # Relabel Example 1    
    relabel_configs:
      # Use Tag Name as instance label
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
        # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id   
        # Use the instance private ip as the ip label
      - source_labels: [__meta_ec2_private_ip]
        target_label: ip   
        # Use the instance public ip as the public ip label
      - source_labels: [__meta_ec2_public_ip]
        target_label: public_ip