global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # Start scraping Ec2 Instances using service discovery mechanism
  -job_name: 'ec2_instances'
   ec2_sd_configs:
     - region: us-east-1
       port: 9100